name: GCP deployment GAR

on:
  push:
    branches:
      - "main"

jobs:
  gcp-dev-deployment:
    name: Build and push image, deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      REGION: asia-south1
      REPOSITORY: docker-artifact-regsitry
      IMAGE: main

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Autheticatw with google
      - name: "Autheticate with Google"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Configure Docker
        run: |
          gcloud auth configure-docker -q
      # Build docker image
      - name: Build docker image for api
        run: |-
          docker build -t "$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" .
      - name: Authenticating docker with gcloud
        run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin "https://$REGION-docker.pkg.dev"

      # Push image to Google Artifact Registry repository
      - name: Push api image to Google Artifact Registry repository
        run: |-
          docker push "$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
      # Deploy to cloud run
      - name: Deploy api to cloud run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: "${{ env.SERVICE_NAME }}"
          image: "${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE}}:${{ github.sha }}"
          region: "${{ env.REGION }}"

          #done done
